"""
Builds data/openings.js from the Lichess opening list (github.com/lichess-org/chess-openings, CC0):
every position on a named opening line -> opening name ("" for an unnamed position inside a line).
Used to mark "book" moves in the game review.

Run:  python -m pip install chess
      python tools/build_openings.py <folder with a.tsv ... e.tsv>
"""
import csv
import json
import os
import sys
import chess
import chess.pgn
import io

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "data", "openings.js")


def key(board):
    # placement, side to move, castling (en passant left out on purpose)
    return " ".join(board.fen().split(" ")[:3])


def main(src):
    names = {}
    inner = set()
    for letter in "abcde":
        with open(os.path.join(src, f"{letter}.tsv"), encoding="utf-8") as f:
            for row in csv.DictReader(f, delimiter="\t"):
                game = chess.pgn.read_game(io.StringIO(row["pgn"]))
                board = game.board()
                for mv in game.mainline_moves():
                    board.push(mv)
                    inner.add(key(board))
                names[key(board)] = row["name"]
    book = {k: "" for k in inner}
    book.update(names)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/build_openings.py from lichess-org/chess-openings (CC0).\n")
        f.write("window.OPENINGS = ")
        json.dump(book, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    print(f"{len(names)} named, {len(book)} book positions -> {OUT} ({os.path.getsize(OUT) // 1024} KB)")


if __name__ == "__main__":
    main(sys.argv[1])
