"""
Builds data/top-puzzles.js — a curated set of the highest-rated Lichess puzzles
per category, straight from the official Lichess puzzle database (mirrored on
Hugging Face as Lichess/chess-puzzles).

"Best" = highest community vote score (Popularity) among puzzles that many
players have actually solved (NbPlays), so the ranking is reliable.

Run:  python -m pip install duckdb  &&  python tools/build_puzzles.py
"""
import json
import os
import duckdb

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "data", "top-puzzles.js")
BASE = "https://huggingface.co/datasets/Lichess/chess-puzzles/resolve/main/data/"
FILES = [BASE + f"train-0000{i}-of-00003.parquet" for i in range(3)]

PER_CATEGORY = 150

# key -> (theme filter, min rating, max rating, min plays)
CATEGORIES = {
    # long, brain-burning calculation
    "veryLong_hard":   ("veryLong", 2000, 3400, 3000),
    "veryLong_mid":    ("veryLong", 1500, 2000, 5000),
    "veryLong_easy":   ("veryLong", 0, 1500, 5000),
    "long":            ("long", 1400, 3400, 5000),
    "mateIn3":         ("mateIn3", 0, 3400, 5000),
    "mateIn4":         ("mateIn4", 0, 3400, 3000),
    "mateIn5":         ("mateIn5", 0, 3400, 1500),
    "superGM":         ("superGM", 0, 3400, 1500),
    "masterVsMaster":  ("masterVsMaster", 0, 3400, 3000),
    # anti-blunder / defence
    "hangingPiece":    ("hangingPiece", 0, 3400, 8000),
    "defensiveMove":   ("defensiveMove", 0, 3400, 5000),
    "equality":        ("equality", 0, 3400, 5000),
    "trappedPiece":    ("trappedPiece", 0, 3400, 5000),
    # tactical motifs
    "fork":            ("fork", 0, 3400, 8000),
    "pin":             ("pin", 0, 3400, 8000),
    "skewer":          ("skewer", 0, 3400, 8000),
    "discoveredAttack": ("discoveredAttack", 0, 3400, 8000),
    "doubleCheck":     ("doubleCheck", 0, 3400, 5000),
    "sacrifice":       ("sacrifice", 0, 3400, 8000),
    "deflection":      ("deflection", 0, 3400, 8000),
    "attraction":      ("attraction", 0, 3400, 8000),
    "intermezzo":      ("intermezzo", 0, 3400, 5000),
    "quietMove":       ("quietMove", 0, 3400, 5000),
    "clearance":       ("clearance", 0, 3400, 5000),
    "interference":    ("interference", 0, 3400, 3000),
    "xRayAttack":      ("xRayAttack", 0, 3400, 3000),
    "capturingDefender": ("capturingDefender", 0, 3400, 5000),
    "zugzwang":        ("zugzwang", 0, 3400, 3000),
    # mating patterns
    "mateIn1":         ("mateIn1", 0, 3400, 10000),
    "mateIn2":         ("mateIn2", 0, 3400, 10000),
    "backRankMate":    ("backRankMate", 0, 3400, 8000),
    "smotheredMate":   ("smotheredMate", 0, 3400, 3000),
    "kingsideAttack":  ("kingsideAttack", 0, 3400, 8000),
    "exposedKing":     ("exposedKing", 0, 3400, 8000),
    # phases
    "opening":         ("opening", 0, 3400, 8000),
    "middlegame":      ("middlegame", 1500, 3400, 8000),
    "endgame":         ("endgame", 0, 3400, 8000),
    "rookEndgame":     ("rookEndgame", 0, 3400, 5000),
    "pawnEndgame":     ("pawnEndgame", 0, 3400, 5000),
    "advancedPawn":    ("advancedPawn", 0, 3400, 5000),
    "promotion":       ("promotion", 0, 3400, 5000),
    "crushing":        ("crushing", 1600, 3400, 8000),
}


def main():
    con = duckdb.connect()
    con.execute("INSTALL httpfs; LOAD httpfs;")
    files = ", ".join(f"'{f}'" for f in FILES)
    print("scanning Lichess puzzle DB (remote parquet)...")
    con.execute(f"""
        CREATE TABLE cand AS
        SELECT PuzzleId, FEN, Moves, Rating, Popularity, NbPlays, Themes, GameId
        FROM read_parquet([{files}])
        WHERE Popularity >= 90 AND NbPlays >= 1500 AND RatingDeviation <= 90
    """)
    print("candidates:", con.execute("SELECT count(*) FROM cand").fetchone()[0])

    out = {}
    for key, (theme, rmin, rmax, pmin) in CATEGORIES.items():
        rows = con.execute(f"""
            SELECT PuzzleId, FEN, Moves, Rating, Popularity, NbPlays, Themes, GameId
            FROM cand
            WHERE list_contains(Themes, ?) AND Rating >= ? AND Rating < ? AND NbPlays >= ?
            ORDER BY Popularity DESC, NbPlays DESC
            LIMIT {PER_CATEGORY}
        """, [theme, rmin, rmax, pmin]).fetchall()
        out[key] = [
            {
                "id": r[0], "fen": r[1], "moves": r[2], "rating": r[3],
                "pop": r[4], "plays": r[5],
                "themes": list(r[6]) if not isinstance(r[6], str) else r[6].split(),
                "game": r[7],
            }
            for r in rows
        ]
        print(f"{key:18s} {len(rows)}")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/build_puzzles.py from the Lichess puzzle database (CC0).\n")
        f.write("window.TOP_PUZZLES = ")
        json.dump(out, f, separators=(",", ":"))
        f.write(";\n")
    print("wrote", OUT, os.path.getsize(OUT) // 1024, "KB")


if __name__ == "__main__":
    main()
